### ISSUE TITLE
[feature] Expand filter to accept different sources and projects

### ISSUE THREAD

**Issue by amreesh** [bgpkit/bgpkit-broker-backend#11]
When searching for BGP update messages, it would be great to set as filter multiple sources (e.g. rrc00, rrc14) and as well as multiple projects (e.g. riperis, route-views). This is because some prefixes are visible only on some sources/projects only.

**Comment by digizeph** [comment]
@amreesh the new version of the broker API is deployed with the capability to search for data from multiple collectors. It's not a breaking change at your side, and now you should be able to use comma separated string to specify multiple collectors when using the parser API.

Feel free to re-open this issue if you find other problems on this matter.
